services:
  web:
    build: ./files/w1
    container_name: web
    ports:
      - "8080:8080"
    networks:
      - test-network

  proxy:
    build: ./files/proxy
    container_name: proxy
    ports:
      - "80:80"
    networks:
      - test-network
    depends_on:
      - web

networks:
  test-network:
    driver: bridge